
/*
 * SPDX-FileCopyrightText: syuilo and misskey-project & noridev and cherrypick-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// This file was automatically generated by create-search-index.
// Do not edit this file.

import { i18n } from '@/i18n.js';

export type SearchIndexItem = {
	id: string;
	path?: string;
	label: string;
	keywords: string[];
	icon?: string;
	children?: SearchIndexItem[];
};

export const searchIndexes: SearchIndexItem[] = [
	{
		id: 'nqd1EthAl',
		children: [
			{
				id: 'i9BTjCthm',
				label: i18n.ts._timelines.home,
				keywords: ['enable', 'home'],
			},
			{
				id: 'pbZkAEIv',
				label: i18n.ts._timelines.local,
				keywords: ['enable', 'local'],
			},
			{
				id: '51TBiPcmy',
				label: i18n.ts._timelines.social,
				keywords: ['enable', 'social'],
			},
			{
				id: 'eJmNR2K4s',
				label: i18n.ts._timelines.global,
				keywords: ['enable', 'global'],
			},
			{
				id: 'DcMJ15v74',
				label: i18n.ts._timelines.bubble,
				keywords: ['enable', 'bubble'],
			},
			{
				id: 'jEUHDjbZp',
				label: i18n.ts.lists,
				keywords: ['enable', 'list'],
			},
			{
				id: 'zCL17RSw8',
				label: i18n.ts.antennas,
				keywords: ['enable', 'antenna'],
			},
			{
				id: '7qtfCXog',
				label: i18n.ts.channel,
				keywords: ['enable', 'channel'],
			},
		],
		label: i18n.ts.timeline,
		keywords: ['timeline'],
		path: '/settings/timeline',
		icon: 'ti ti-align-left',
	},
	{
		id: 'flXd1LC7r',
		children: [
			{
				id: 'hB11H5oul',
				label: i18n.ts.syncDeviceDarkMode,
				keywords: ['sync', 'device', 'dark', 'light', 'mode'],
			},
			{
				id: 'fDbLtIKeo',
				label: i18n.ts.themeForLightMode,
				keywords: ['light', 'theme'],
			},
			{
				id: 'CsSVILKpX',
				label: i18n.ts.themeForDarkMode,
				keywords: ['dark', 'theme'],
			},
			{
				id: '8wcoRp76b',
				label: i18n.ts.setWallpaper,
				keywords: ['wallpaper'],
			},
		],
		label: i18n.ts.theme,
		keywords: ['theme'],
		path: '/settings/theme',
		icon: 'ti ti-palette',
	},
	{
		id: 'gXe25uX7X',
		children: [
			{
				id: 'x5D6qdMms',
				label: i18n.ts.notUseSound,
				keywords: ['mute'],
			},
			{
				id: 'gonp8RgsE',
				label: i18n.ts.useSoundOnlyWhenActive,
				keywords: ['active', 'mute'],
			},
			{
				id: 'lCG2hDFrx',
				label: i18n.ts.masterVolume,
				keywords: ['volume', 'master'],
			},
		],
		label: i18n.ts._vibrations.system,
		keywords: ['sounds', i18n.ts.cannotBeUsedFunc],
		path: '/settings/sounds-and-vibrations',
		icon: 'ti ti-music',
	},
	{
		id: '5BjnxMfYV',
		children: [
			{
				id: '3UqdSCaFw',
				children: [
					{
						id: '75QPEg57v',
						label: i18n.ts.changePassword,
						keywords: [],
					},
				],
				label: i18n.ts.password,
				keywords: ['password'],
			},
			{
				id: '2fa',
				children: [
					{
						id: 'qCXM0HtJ7',
						label: i18n.ts.totp,
						keywords: ['totp', 'app', i18n.ts.totpDescription],
					},
					{
						id: '3g1RePuD9',
						label: i18n.ts.securityKeyAndPasskey,
						keywords: ['security', 'key', 'passkey'],
					},
					{
						id: 'pFRud5u8k',
						label: i18n.ts.passwordLessLogin,
						keywords: ['password', 'less', 'key', 'passkey', 'login', 'signin', i18n.ts.passwordLessLoginDescription],
					},
				],
				label: i18n.ts['2fa'],
				keywords: ['2fa'],
			},
		],
		label: i18n.ts.security,
		keywords: ['security'],
		path: '/settings/security',
		icon: 'ti ti-lock',
	},
	{
		id: 'w4L6myH61',
		children: [
			{
				id: 'ru8DrOn3J',
				label: i18n.ts._profile.changeBanner,
				keywords: ['banner', 'change'],
			},
			{
				id: 'CCnD8Apnu',
				label: i18n.ts._profile.changeAvatar,
				keywords: ['avatar', 'icon', 'change'],
			},
			{
				id: 'yFEVCJxFX',
				label: i18n.ts._profile.name,
				keywords: ['name'],
			},
			{
				id: '2O1S5reaB',
				label: i18n.ts._profile.description,
				keywords: ['description', 'bio'],
			},
			{
				id: 'pWi4OLS8g',
				label: i18n.ts.location,
				keywords: ['location', 'locale'],
			},
			{
				id: 'oLO5X6Wtw',
				label: i18n.ts.birthday,
				keywords: ['birthday', 'birthdate', 'age'],
			},
			{
				id: 'm2trKwPgq',
				label: i18n.ts.language,
				keywords: ['language', 'locale'],
			},
			{
				id: 'kfDZxCDp9',
				label: i18n.ts._profile.metadataEdit,
				keywords: ['metadata'],
			},
			{
				id: 'uPt3MFymp',
				label: i18n.ts._profile.followedMessage,
				keywords: ['follow', 'message', i18n.ts._profile.followedMessageDescription],
			},
			{
				id: 'wuGg0tBjw',
				label: i18n.ts.reactionAcceptance,
				keywords: ['reaction'],
			},
			{
				id: 'EezPpmMnf',
				children: [
					{
						id: 'f2cRLh8ad',
						label: i18n.ts.flagAsCat,
						keywords: ['cat'],
					},
					{
						id: 'eVoViiF3h',
						label: i18n.ts.flagAsBot,
						keywords: ['bot'],
					},
				],
				label: i18n.ts.advancedSettings,
				keywords: [],
			},
		],
		label: i18n.ts.profile,
		keywords: ['profile'],
		path: '/settings/profile',
		icon: 'ti ti-user',
	},
	{
		id: '2rp9ka5Ht',
		children: [
			{
				id: 'qBUSKPxLW',
				label: i18n.ts.makeFollowManuallyApprove,
				keywords: ['follow', 'lock', i18n.ts.lockedAccountInfo],
			},
			{
				id: '3LZBlZCej',
				label: i18n.ts.autoAcceptFollowed,
				keywords: ['follow', 'auto', 'accept'],
			},
			{
				id: '9gOp28wKG',
				label: i18n.ts.makeReactionsPublic,
				keywords: ['reaction', 'public', i18n.ts.makeReactionsPublicDescription],
			},
			{
				id: 'CjAkqMhct',
				label: i18n.ts.followingVisibility,
				keywords: ['following', 'visibility'],
			},
			{
				id: '4nEwI6LYt',
				label: i18n.ts.followersVisibility,
				keywords: ['follower', 'visibility'],
			},
			{
				id: 'naMp37wTL',
				label: i18n.ts.hideOnlineStatus,
				keywords: ['online', 'status', i18n.ts.hideOnlineStatusDescription],
			},
			{
				id: 'p0dCVR0UP',
				label: i18n.ts.noCrawle,
				keywords: ['crawle', 'index', 'search', i18n.ts.noCrawleDescription],
			},
			{
				id: 'aceURmNPq',
				label: i18n.ts.preventAiLearning,
				keywords: ['crawle', 'ai', i18n.ts.preventAiLearningDescription],
			},
			{
				id: 'ahABA0j7u',
				label: i18n.ts.makeExplorable,
				keywords: ['explore', i18n.ts.makeExplorableDescription],
			},
			{
				id: 'cyeDbLN8N',
				children: [
					{
						id: 'xEYlOghao',
						label: i18n.ts._accountSettings.requireSigninToViewContents,
						keywords: ['login', 'signin'],
					},
					{
						id: 'sMmYFCS60',
						label: i18n.ts._accountSettings.makeNotesFollowersOnlyBefore,
						keywords: ['follower', i18n.ts._accountSettings.makeNotesFollowersOnlyBeforeDescription],
					},
					{
						id: 'ebJ9IUbik',
						label: i18n.ts._accountSettings.makeNotesHiddenBefore,
						keywords: ['hidden', i18n.ts._accountSettings.makeNotesHiddenBeforeDescription],
					},
				],
				label: i18n.ts.lockdown,
				keywords: ['lockdown'],
			},
		],
		label: i18n.ts.privacy,
		keywords: ['privacy'],
		path: '/settings/privacy',
		icon: 'ti ti-lock-open',
	},
	{
		id: '3yCAv0IsZ',
		children: [
			{
				id: 'x1GWSQnPw',
				label: i18n.ts.uiLanguage,
				keywords: ['language'],
			},
			{
				id: 'EOSa4rtt3',
				label: i18n.ts.overridedDeviceKind,
				keywords: ['device', 'type', 'kind', 'smartphone', 'tablet', 'desktop'],
			},
			{
				id: 'm9LhX8BG8',
				label: i18n.ts.showFixedPostForm,
				keywords: ['post', 'form', 'timeline'],
			},
			{
				id: 'snyCQ5oKE',
				label: i18n.ts.showFixedPostFormInChannel,
				keywords: ['post', 'form', 'timeline', 'channel'],
			},
			{
				id: '8j36S4Ev6',
				label: i18n.ts.showFixedPostFormInReplies,
				keywords: ['post', 'form', 'replies', 'note', i18n.ts.showFixedPostFormInRepliesDescription],
			},
			{
				id: 'CWpyT9vLK',
				label: i18n.ts.pinnedList,
				keywords: ['pinned', 'list'],
			},
			{
				id: 'puIqj1a8b',
				label: i18n.ts.enableQuickAddMfmFunction,
				keywords: ['mfm', 'mfc', 'enable', 'show', 'advanced', 'picker', 'form', 'function', 'fn'],
			},
			{
				id: 'cjfAtxMzP',
				label: i18n.ts.rememberNoteVisibility,
				keywords: ['remember', 'keep', 'note', 'visibility'],
			},
			{
				id: 'zx0e321ao',
				label: i18n.ts.defaultNoteVisibility,
				keywords: ['default', 'note', 'visibility'],
			},
			{
				id: 'l78F2W9Ok',
				children: [
					{
						id: 'q5ElfNSou',
						label: i18n.ts.forceCollapseAllRenotes,
						keywords: ['force', 'collapse', 'renote', i18n.ts.forceCollapseAllRenotesDescription],
					},
					{
						id: 'CQldliCSi',
						label: i18n.ts.collapseRenotes,
						keywords: ['collapse', 'renote', i18n.ts.collapseRenotesDescription],
					},
					{
						id: '7Jwvu8bK6',
						label: i18n.ts.collapseReplies,
						keywords: ['collapse', 'reply', 'replies', i18n.ts.collapseRepliesDescription],
					},
					{
						id: 'dI0hKRjJ6',
						label: i18n.ts.collapseLongNoteContent,
						keywords: ['collapse', 'long', 'note', 'content'],
					},
					{
						id: 'wZqrDQZar',
						label: i18n.ts.collapseDefault,
						keywords: ['collapse', 'note'],
					},
					{
						id: '3SBAYM8Fk',
						label: i18n.ts.allMediaNoteCollapse,
						keywords: ['media', 'note', 'collapse'],
					},
					{
						id: 'c8gA9Xj2a',
						label: i18n.ts.showNoteActionsOnlyHover,
						keywords: ['hover', 'show', 'footer', 'action'],
					},
					{
						id: 'pz7gre7LW',
						label: i18n.ts.showClipButtonInNoteFooter,
						keywords: ['footer', 'action', 'clip', 'show'],
					},
					{
						id: 'ae14yoS4s',
						label: i18n.ts.showSubNoteFooterButton,
						keywords: ['footer', 'action', 'sub', 'note', 'show', i18n.ts.showSubNoteFooterButtonDescription],
					},
					{
						id: 'bFsNusspF',
						label: i18n.ts.infoButtonForNoteActions,
						keywords: ['footer', 'action', 'info', 'note', 'enable', i18n.ts.infoButtonForNoteActionsDescription],
					},
					{
						id: 'dHPv9mrxi',
						label: i18n.ts.showTranslateButtonInNote,
						keywords: ['note', 'action', 'translate', 'show'],
					},
					{
						id: 'yxehrHZ6x',
						label: i18n.ts.reply,
						keywords: ['reply'],
					},
					{
						id: 'DdoFLaSG8',
						label: i18n.ts.renote,
						keywords: ['renote'],
					},
					{
						id: 'uIMCIK7kG',
						label: i18n.ts.like,
						keywords: ['like'],
					},
					{
						id: 'zvM13vl26',
						label: i18n.ts.doReaction,
						keywords: ['reaction', 'react'],
					},
					{
						id: 'k55mQTk4B',
						label: i18n.ts.quote,
						keywords: ['quote'],
					},
					{
						id: 'tJmNnHLqx',
						label: i18n.ts.more,
						keywords: ['more'],
					},
					{
						id: 'vE7KeV4U4',
						label: i18n.ts.like,
						keywords: ['like', 'select', 'reaction', 'react'],
					},
					{
						id: '91zwCdbR4',
						label: i18n.ts.renoteQuoteButtonSeparation,
						keywords: ['renote', 'quote', 'separation', 'note'],
					},
					{
						id: 'cBkUgQNpH',
						label: i18n.ts.showRenoteVisibilitySelector,
						keywords: ['renote', 'visibility', 'selection', 'note'],
					},
					{
						id: '9WrGgANqN',
						label: i18n.ts.forceRenoteVisibilitySelector,
						keywords: ['force', 'renote', 'visibility', 'selection', 'note'],
					},
					{
						id: 'iaAudjvEV',
						label: i18n.ts.showNoAltWarning,
						keywords: ['show', 'alt', 'text', 'warning', i18n.ts.showNoAltWarningDescription],
					},
					{
						id: 'cIWkvfsDI',
						label: i18n.ts.alwaysShowCw,
						keywords: ['always', 'show', 'cw', 'nsfw'],
					},
					{
						id: 'fk6OxoQVe',
						label: i18n.ts.enableAdvancedMfm,
						keywords: ['mfm', 'mfc', 'enable', 'show', 'advanced'],
					},
					{
						id: 'mRj9pVrG3',
						label: i18n.ts.showReactionsCount,
						keywords: ['reaction', 'count', 'show'],
					},
					{
						id: 'e5XnQWk68',
						label: i18n.ts.loadRawImages,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'quality', 'raw', 'attachment'],
					},
				],
				label: i18n.ts.note,
				keywords: ['note'],
			},
			{
				id: 'vAUal2B3x',
				children: [
					{
						id: 'eb0yCYJTn',
						label: i18n.ts.useGroupedNotifications,
						keywords: ['group'],
					},
					{
						id: 'pZLzt3i0s',
						label: i18n.ts.showReplyInNotification,
						keywords: ['show', 'reply', 'notification', 'note'],
					},
				],
				label: i18n.ts.notifications,
				keywords: ['notification'],
			},
			{
				id: 'cWiM1XhZl',
				children: [
					{
						id: '2E7vdIUQd',
						label: i18n.ts.openImageInNewTab,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'new', 'tab'],
					},
					{
						id: 'xt3ktC8Fp',
						label: i18n.ts.useReactionPickerForContextMenu,
						keywords: ['reaction', 'picker', 'contextmenu', 'open'],
					},
					{
						id: 'qe0AVHF5g',
						label: i18n.ts.enableInfiniteScroll,
						keywords: ['load', 'auto', 'more'],
					},
					{
						id: 'ePfCsZqSU',
						label: i18n.ts.disableStreamingTimeline,
						keywords: ['disable', 'streaming', 'timeline'],
					},
					{
						id: 'KHvrWlW7',
						label: i18n.ts.alwaysConfirmFollow,
						keywords: ['follow', 'confirm', 'always'],
					},
					{
						id: 'Cbjosj3TG',
						label: i18n.ts.confirmWhenRevealingSensitiveMedia,
						keywords: ['sensitive', 'nsfw', 'media', 'image', 'photo', 'picture', 'attachment', 'confirm'],
					},
					{
						id: 'yygNLYGju',
						label: i18n.ts.confirmOnReact,
						keywords: ['reaction', 'confirm'],
					},
					{
						id: 'CEYxpc3Q4',
						label: i18n.ts.keepCw,
						keywords: ['remember', 'keep', 'note', 'cw'],
					},
					{
						id: 'fY9Gv4pRF',
						label: i18n.ts.autoLoadMoreReplies,
						keywords: ['auto', 'load', 'more', 'reply', 'replies'],
					},
					{
						id: 'fm98eqzke',
						label: i18n.ts.autoLoadMoreConversation,
						keywords: ['auto', 'load', 'more', 'conversation'],
					},
					{
						id: 'gH0bEr61Y',
						label: i18n.ts.useAutoTranslate,
						keywords: ['auto', 'translate'],
					},
					{
						id: 'rR3l92ZXV',
						label: i18n.ts.welcomeBackToast,
						keywords: ['welcome', 'toast'],
					},
					{
						id: 'wa5MxCr9Q',
						label: i18n.ts.noNyaization,
						keywords: ['disable', 'nyaize', 'note'],
					},
					{
						id: 'hdQa7W2H1',
						label: i18n.ts.whenServerDisconnected,
						keywords: ['server', 'disconnect', 'reconnect', 'reload', 'streaming'],
					},
					{
						id: 'sZcalFBE8',
						label: i18n.ts.requireRefresh,
						keywords: ['refresh'],
					},
					{
						id: 'oOgCa1BvJ',
						label: i18n.ts.newNoteReceivedNotification,
						keywords: ['note', 'receive', 'notification'],
					},
					{
						id: '3oLZS5QhW',
						label: i18n.ts.numberOfPageCache,
						keywords: ['cache', 'page'],
					},
					{
						id: 'zVxlhD3Li',
						label: i18n.ts.dataSaver,
						keywords: ['datasaver'],
					},
					{
						id: 'q0yCZ1BS9',
						label: i18n.ts._externalNavigationWarning.trustedDomainList,
						keywords: ['external', 'navigation', 'warning', i18n.ts._externalNavigationWarning.trustedDomainListDescription],
					},
				],
				label: i18n.ts.behavior,
				keywords: ['behavior'],
			},
			{
				id: 'vCTonyyvb',
				children: [
					{
						id: 'h1uqXsAXn',
						label: i18n.ts.forceShowAds,
						keywords: ['ad', 'show'],
					},
					{
						id: 'c5hdagIXI',
						label: i18n.ts.hemisphere,
						keywords: [],
					},
					{
						id: '6BIxLzPJr',
						children: [
							{
								id: 'eRsKTEmf2',
								label: i18n.ts._searchSite.otherSearchEngine,
								keywords: [i18n.ts._searchSite.otherDescription],
							},
							{
								id: 'kfTVtLvgI',
								label: i18n.ts._searchSite.query,
								keywords: [i18n.ts._searchSite.queryDescription],
							},
						],
						label: i18n.ts._searchSite.title,
						keywords: ['search', 'engine', i18n.ts._searchSite.description],
					},
					{
						id: 'urkK4xGn9',
						label: i18n.ts.additionalEmojiDictionary,
						keywords: ['emoji', 'dictionary', 'additional', 'extra'],
					},
				],
				label: i18n.ts.other,
				keywords: [],
			},
		],
		label: i18n.ts.preferences,
		keywords: ['general', 'preferences'],
		path: '/settings/preferences',
		icon: 'ti ti-adjustments',
	},
	{
		id: 'mwkwtw83Y',
		label: i18n.ts.plugins,
		keywords: ['plugin'],
		path: '/settings/plugin',
		icon: 'ti ti-plug',
	},
	{
		id: 'F1uK9ssiY',
		children: [
			{
				id: 'msAcN6u3S',
				label: i18n.ts.accountInfo,
				keywords: ['account', 'info'],
			},
			{
				id: 'fU8ipoIqw',
				label: i18n.ts.accountMigration,
				keywords: ['account', 'move', 'migration'],
			},
			{
				id: '6BvIBTqCE',
				label: i18n.ts.closeAccount,
				keywords: ['account', 'close', 'delete', i18n.ts._accountDelete.requestAccountDelete],
			},
			{
				id: 'bamftnec4',
				label: 'Unnamed marker',
				keywords: ['account', 'truncate', 'delete'],
			},
			{
				id: 'cC8DwTVqD',
				label: i18n.ts.experimentalFeatures,
				keywords: ['experimental', 'feature', 'flags'],
			},
			{
				id: 'DzjEbTJ9h',
				label: i18n.ts.developer,
				keywords: ['developer', 'mode', 'debug'],
			},
		],
		label: i18n.ts.other,
		keywords: ['other'],
		path: '/settings/other',
		icon: 'ti ti-dots',
	},
	{
		id: '9bNikHWzQ',
		children: [
			{
				id: '8esviBNuv',
				label: i18n.ts.display,
				keywords: ['menu', 'display'],
			},
			{
				id: 'nnh2pahtP',
				label: i18n.ts.displayBanner,
				keywords: ['banner', 'display'],
			},
			{
				id: 's1wwdX2sM',
				label: i18n.ts.postNote,
				keywords: ['bottom'],
			},
		],
		label: i18n.ts.navbar,
		keywords: ['navbar'],
		path: '/settings/navbar',
		icon: 'ti ti-list',
	},
	{
		id: '3icEvyv2D',
		children: [
			{
				id: 'Tyt3gZTy',
				children: [
					{
						id: '9b7ZURyAt',
						label: i18n.ts.showMutedWord,
						keywords: ['show'],
					},
				],
				label: i18n.ts.wordMute,
				keywords: ['note', 'word', 'soft', 'mute', 'hide'],
			},
			{
				id: 'kdMk41II0',
				label: i18n.ts.hardWordMute,
				keywords: ['note', 'word', 'hard', 'mute', 'hide'],
			},
			{
				id: 'mjORQamAK',
				label: i18n.ts.instanceMute,
				keywords: ['note', 'server', 'instance', 'host', 'federation', 'mute', 'hide'],
			},
			{
				id: '1ZT7S9FZd',
				label: `${i18n.ts.mutedUsers} (${ i18n.ts.renote })`,
				keywords: ['renote', 'mute', 'hide', 'user'],
			},
			{
				id: 'ANrPit3kQ',
				label: i18n.ts.mutedUsers,
				keywords: ['note', 'mute', 'hide', 'user'],
			},
			{
				id: 'bPAE4lfno',
				label: i18n.ts.blockedUsers,
				keywords: ['block', 'user'],
			},
		],
		label: i18n.ts.muteAndBlock,
		keywords: ['mute', 'block'],
		path: '/settings/mute-block',
		icon: 'ti ti-ban',
	},
	{
		id: 'qE2vLlMkF',
		children: [
			{
				id: 'hPPEzjvZC',
				label: i18n.ts._exportOrImport.allNotes,
				keywords: ['notes'],
			},
			{
				id: 'AFaeHsCUB',
				label: i18n.ts._exportOrImport.favoritedNotes,
				keywords: ['favorite', 'notes'],
			},
			{
				id: 'xyCPmQiRo',
				label: i18n.ts._exportOrImport.clips,
				keywords: ['clip', 'notes'],
			},
			{
				id: 'Ch7hWAGUy',
				label: i18n.ts._exportOrImport.followingList,
				keywords: ['following', 'users'],
			},
			{
				id: 'AwPgFboEx',
				label: i18n.ts._exportOrImport.userLists,
				keywords: ['user', 'lists'],
			},
			{
				id: 'nporiHshC',
				label: i18n.ts._exportOrImport.muteList,
				keywords: ['mute', 'users'],
			},
			{
				id: 'BsCzR7vNw',
				label: i18n.ts._exportOrImport.blockingList,
				keywords: ['block', 'users'],
			},
			{
				id: 'dvf4IgYrQ',
				label: i18n.ts.antennas,
				keywords: ['antennas'],
			},
		],
		label: i18n.ts.importAndExport,
		keywords: ['import', 'export', 'data'],
		path: '/settings/import-export',
		icon: 'ti ti-package',
	},
	{
		id: '3Tcxw4Fwl',
		children: [
			{
				id: 'iIai9O65I',
				label: i18n.ts.emailAddress,
				keywords: ['email', 'address'],
			},
			{
				id: 'i6cC6oi0m',
				label: i18n.ts.receiveAnnouncementFromInstance,
				keywords: ['announcement', 'email'],
			},
			{
				id: 'C1YTinP11',
				label: i18n.ts.emailNotification,
				keywords: ['notification', 'email'],
			},
		],
		label: i18n.ts.email,
		keywords: ['email'],
		path: '/settings/email',
		icon: 'ti ti-mail',
	},
	{
		id: 'tnYoppRiv',
		children: [
			{
				id: 'ncIq6TAR2',
				label: i18n.ts.usageAmount,
				keywords: ['capacity', 'usage'],
			},
			{
				id: '2c4CQSvSr',
				label: i18n.ts.statistics,
				keywords: ['statistics', 'usage'],
			},
			{
				id: 'pepHELHMt',
				label: i18n.ts.uploadFolder,
				keywords: ['default', 'upload', 'folder'],
			},
			{
				id: 'xqOWrABxV',
				label: i18n.ts.keepOriginalUploading,
				keywords: ['keep', 'original', 'raw', 'upload', i18n.ts.keepOriginalUploadingDescription],
			},
			{
				id: 'D8HUTGWE1',
				label: i18n.ts.keepOriginalFilename,
				keywords: ['keep', 'original', 'filename', i18n.ts.keepOriginalFilenameDescription],
			},
			{
				id: '6xAvsWSZi',
				label: 'Unnamed marker',
				keywords: ['compression', 'compress', 'original', 'lossy', 'resize'],
			},
			{
				id: '8NcSbIJZO',
				label: i18n.ts.alwaysMarkSensitive,
				keywords: ['always', 'default', 'mark', 'nsfw', 'sensitive', 'media', 'file'],
			},
			{
				id: '4oe5GDSCc',
				label: i18n.ts.enableAutoSensitive,
				keywords: ['auto', 'nsfw', 'sensitive', 'media', 'file', i18n.ts.enableAutoSensitiveDescription],
			},
		],
		label: i18n.ts.drive,
		keywords: ['drive'],
		path: '/settings/drive',
		icon: 'ti ti-cloud',
	},
	{
		id: '2HuxtgWa1',
		children: [
			{
				id: '9qNB7raTE',
				label: i18n.ts._cherrypick.nickname,
				keywords: ['nickname', 'enable', i18n.ts._cherrypick.nicknameDescription],
			},
			{
				id: 'DyKDeHONI',
				label: 'Unnamed marker',
				keywords: ['nickname', 'enable'],
			},
			{
				id: 'qBKqephVl',
				label: i18n.ts._cherrypick.postFormVisibilityHotkey,
				keywords: ['post', 'form', 'visibility', 'hotkey', i18n.ts._cherrypick.postFormVisibilityHotkeyDescription],
			},
			{
				id: 'eEA7ytlZ5',
				label: i18n.ts._cherrypick.showRenoteConfirmPopup,
				keywords: ['show', 'renote', 'note', 'confirm', 'popup', i18n.ts._cherrypick.showRenoteConfirmPopupDescription],
			},
			{
				id: 'lgY6Zesu0',
				children: [
					{
						id: '4YCeZiMxo',
						label: i18n.ts._cherrypick.expandOnNoteClickBehavior,
						keywords: ['behavior'],
					},
				],
				label: i18n.ts._cherrypick.expandOnNoteClick,
				keywords: ['expand', 'note', 'click', i18n.ts._cherrypick.expandOnNoteClickDescription],
			},
			{
				id: 'kxtO1YGjn',
				label: i18n.ts._cherrypick.displayHeaderNavBarWhenScroll,
				keywords: ['display', 'header', 'navbar', 'scroll'],
			},
			{
				id: 'ucJrWjNkp',
				children: [
					{
						id: 'abmEqjbI9',
						label: i18n.ts._cherrypick.reactableRemoteReaction,
						keywords: ['reactable', 'remote', 'reaction', 'react', 'enable'],
					},
					{
						id: 'vrQyQ7OAC',
						label: i18n.ts._cherrypick.showFollowingMessageInsteadOfButton,
						keywords: ['show', 'follow', 'message', 'enable'],
					},
					{
						id: '9MWRArjLD',
						label: i18n.ts._cherrypick.mobileHeaderChange,
						keywords: ['mobile', 'header', 'change'],
					},
					{
						id: '5db7W0B5j',
						label: i18n.ts._cherrypick.renameTheButtonInPostFormToNya,
						keywords: ['rename', 'post', 'form', 'nya', i18n.ts._cherrypick.renameTheButtonInPostFormToNyaDescription],
					},
				],
				label: i18n.ts._cherrypick.patch,
				keywords: ['patch', 'behavior', i18n.ts._cherrypick.patchDescription],
			},
			{
				id: 'cBQaz6sa0',
				children: [
					{
						id: 'Cs2cPX8pY',
						label: i18n.ts._cherrypick.enableWidgetsArea,
						keywords: ['enable', 'widget'],
					},
					{
						id: 'hZnNBcUjw',
						children: [
							{
								id: 'x2O7OsvzW',
								label: i18n.ts._cherrypick.friendlyUiEnableNotificationsArea,
								keywords: ['enable', 'notification'],
							},
							{
								id: 'f0HK0WoY2',
								label: i18n.ts._cherrypick.enableLongPressOpenAccountMenu,
								keywords: ['enable', 'long', 'press', 'open', 'account', 'menu', i18n.ts._cherrypick.enableLongPressOpenAccountMenuDescription],
							},
							{
								id: 'aiUEVAQSz',
								label: i18n.ts._cherrypick.friendlyUiShowAvatarDecorationsInNavBtn,
								keywords: ['show', 'avatar', 'decoration', 'navbtn'],
							},
						],
						label: 'Friendly UI',
						keywords: ['friendly'],
					},
				],
				label: 'UI',
				keywords: ['ui', 'show', 'display'],
			},
			{
				id: 'BhJb8gpN0',
				label: i18n.ts.cherrypickLabs,
				keywords: ['behavior', 'lab', i18n.ts.cherrypickLabsDescription],
			},
		],
		label: i18n.ts._cherrypick.function,
		keywords: ['cherrypick', i18n.ts._cherrypick.functionDescription],
		path: '/settings/cherrypick',
		icon: 'ti ti-bulb-filled',
	},
	{
		id: 'gtaOSdIJB',
		label: i18n.ts.avatarDecorations,
		keywords: ['avatar', 'icon', 'decoration'],
		path: '/settings/avatar-decoration',
		icon: 'ti ti-sparkles',
	},
	{
		id: 'AqPvMgn3A',
		children: [
			{
				id: 'vXTFX3YLW',
				children: [
					{
						id: 'sSyWlutU1',
						label: i18n.ts.useBoldFont,
						keywords: ['bold'],
					},
					{
						id: '3ojrhlRkO',
						label: i18n.ts.useSystemFont,
						keywords: ['system', 'native'],
					},
				],
				label: i18n.ts.fontSize,
				keywords: ['font', 'size'],
			},
			{
				id: 'dr8Ns8Yz1',
				label: i18n.ts.useBlurEffect,
				keywords: ['blur'],
			},
			{
				id: 'BminRQZR7',
				label: i18n.ts.useBlurEffectForModal,
				keywords: ['blur', 'modal'],
			},
			{
				id: '44UmMwmUe',
				label: i18n.ts.removeModalBgColorForBlur,
				keywords: ['blur', 'modal', 'bg', 'remove'],
			},
			{
				id: '8xIxd4IHE',
				label: i18n.ts.highlightSensitiveMedia,
				keywords: ['highlight', 'sensitive', 'nsfw', 'image', 'photo', 'picture', 'media', 'thumbnail'],
			},
			{
				id: 'fDelHUrBi',
				label: i18n.ts.squareAvatars,
				keywords: ['avatar', 'icon', 'square'],
			},
			{
				id: 'yuk4om1dx',
				label: i18n.ts.setFederationAvatarShape,
				keywords: ['avatar', 'icon', 'square', 'federation', 'shape', $i?.policies.canSetFederationAvatarShape ? i18n.ts.setFederationAvatarShapeDescription : i18n.ts.cannotBeUsedFunc],
			},
			{
				id: 'mZj648rIe',
				label: i18n.ts.showAvatarDecorations,
				keywords: ['avatar', 'icon', 'decoration', 'show'],
			},
			{
				id: 'eQ33delPQ',
				label: i18n.ts.showGapBetweenNotesInTimeline,
				keywords: ['note', 'timeline', 'gap'],
			},
			{
				id: 'c11GtTlh2',
				label: i18n.ts.seasonalScreenEffect,
				keywords: ['effect', 'show'],
			},
			{
				id: '7PSJygnH3',
				label: i18n.ts.showUnreadNotificationsCount,
				keywords: ['show', 'unread', 'notification', 'count'],
			},
			{
				id: '7AJ2vaPYD',
				label: i18n.ts.filesGridLayoutInUserPage,
				keywords: ['file', 'grid', 'layout', 'user', 'page', i18n.ts.filesGridLayoutInUserPageDescription],
			},
			{
				id: 'EffnKHKhw',
				label: i18n.ts.menuStyle,
				keywords: ['menu', 'style', 'popup', 'drawer'],
			},
			{
				id: '8Y7iPoGwR',
				label: i18n.ts.emojiStyle,
				keywords: ['emoji', 'style', 'native', 'system', 'fluent', 'twemoji'],
			},
			{
				id: '6unWzAfXu',
				children: [
					{
						id: 'A75ebHXeF',
						label: i18n.ts.reactionsDisplaySize,
						keywords: ['reaction', 'size', 'scale', 'display'],
					},
					{
						id: 'tTRh05tPD',
						label: i18n.ts.limitWidthOfReaction,
						keywords: ['reaction', 'size', 'scale', 'display', 'width', 'limit'],
					},
					{
						id: 'lr2Brh1cF',
						label: i18n.ts.hideAvatarsInNote,
						keywords: ['hide', 'avatar', 'note', 'display'],
					},
					{
						id: 'qqJMY1pQM',
						label: i18n.ts.enableAbsoluteTime,
						keywords: ['enable', 'absolute', 'time', 'note', 'display'],
					},
					{
						id: '81Gy76Obg',
						label: i18n.ts.enableMarkByDate,
						keywords: ['enable', 'mark', 'date', 'note', 'display'],
					},
					{
						id: '4dKUP4a4w',
						label: i18n.ts.showReplyTargetNote,
						keywords: ['show', 'reply', 'target', 'note', 'display'],
					},
					{
						id: 'lXJWBpQwd',
						label: i18n.ts.showReplyTargetNoteInSemiTransparent,
						keywords: ['show', 'reply', 'target', 'note', 'transparent', 'display'],
					},
					{
						id: 'skU5WAYzx',
						label: i18n.ts.mediaListWithOneImageAppearance,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'list', 'size', 'height'],
					},
					{
						id: 'qF3TiNmB2',
						label: i18n.ts.instanceTicker,
						keywords: ['ticker', 'information', 'label', 'instance', 'server', 'host', 'federation'],
					},
					{
						id: 'DBRRElWha',
						label: i18n.ts.displayOfSensitiveMedia,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'nsfw', 'sensitive', 'display', 'show', 'hide', 'visibility'],
					},
					{
						id: '573SrjMR9',
						label: 'Unnamed marker',
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'nsfw', 'sensitive', 'display', 'show', 'hide', 'visibility', 'open', 'click', 'double'],
					},
				],
				label: i18n.ts.displayOfNote,
				keywords: ['note', 'display'],
			},
			{
				id: 'zoeGnMuF6',
				children: [
					{
						id: 'DuSCbaip3',
						label: i18n.ts.position,
						keywords: ['position'],
					},
					{
						id: 'dXMRxb8YV',
						label: i18n.ts.stackAxis,
						keywords: ['stack', 'axis', 'direction'],
					},
				],
				label: i18n.ts.notificationDisplay,
				keywords: ['notification', 'display'],
			},
		],
		label: i18n.ts.appearance,
		keywords: ['appearance'],
		path: '/settings/appearance',
		icon: 'ti ti-device-desktop',
	},
	{
		id: 'f08Mi1Uwn',
		children: [
			{
				id: '7ov7ceoij',
				label: i18n.ts.reduceUiAnimation,
				keywords: ['animation', 'motion', 'reduce'],
			},
			{
				id: 'cXr3tFdpa',
				label: i18n.ts.disableShowingAnimatedImages,
				keywords: ['disable', 'animation', 'image', 'photo', 'picture', 'media', 'thumbnail', 'gif'],
			},
			{
				id: 'bgjamYEis',
				label: 'Unnamed marker',
				keywords: ['disable', 'animation', 'image', 'photo', 'picture', 'media', 'thumbnail', 'gif'],
			},
			{
				id: 'Eym5PWl16',
				label: i18n.ts.enableAnimatedMfm,
				keywords: ['mfm', 'mfc', 'enable', 'show', 'animated'],
			},
			{
				id: 'jnMK3M6rs',
				label: i18n.ts.enableHorizontalSwipe,
				keywords: ['swipe', 'horizontal', 'tab'],
			},
			{
				id: '3jdjH2gXc',
				label: i18n.ts.keepScreenOn,
				keywords: ['keep', 'screen', 'display', 'on'],
			},
			{
				id: '4lDaTH78',
				label: i18n.ts.useNativeUIForVideoAudioPlayer,
				keywords: ['native', 'system', 'video', 'audio', 'player', 'media'],
			},
			{
				id: 'a84GlM77n',
				label: i18n.ts._contextMenu.title,
				keywords: ['contextmenu', 'system', 'native'],
			},
		],
		label: i18n.ts.accessibility,
		keywords: ['accessibility'],
		path: '/settings/accessibility',
		icon: 'ti ti-accessible',
	},
] as const;

export type SearchIndex = typeof searchIndexes;
