
/*
 * SPDX-FileCopyrightText: syuilo and misskey-project & noridev and cherrypick-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// This file was automatically generated by create-search-index.
// Do not edit this file.

import { i18n } from '@/i18n.js';

export type SearchIndexItem = {
	id: string;
	path?: string;
	label: string;
	keywords: string[];
	icon?: string;
	children?: SearchIndexItem[];
};

export const searchIndexes: SearchIndexItem[] = [
	{
		id: 'nqd1EthAl',
		children: [
			{
				id: 'i9BTjCthm',
				label: i18n.ts._timelines.home,
				keywords: ['enable', 'home'],
			},
			{
				id: 'pbZkAEIv',
				label: i18n.ts._timelines.local,
				keywords: ['enable', 'local'],
			},
			{
				id: '51TBiPcmy',
				label: i18n.ts._timelines.social,
				keywords: ['enable', 'social'],
			},
			{
				id: 'eJmNR2K4s',
				label: i18n.ts._timelines.global,
				keywords: ['enable', 'global'],
			},
			{
				id: 'DcMJ15v74',
				label: i18n.ts._timelines.bubble,
				keywords: ['enable', 'bubble'],
			},
			{
				id: 'jEUHDjbZp',
				label: i18n.ts.lists,
				keywords: ['enable', 'list'],
			},
			{
				id: 'zCL17RSw8',
				label: i18n.ts.antennas,
				keywords: ['enable', 'antenna'],
			},
			{
				id: '7qtfCXog',
				label: i18n.ts.channel,
				keywords: ['enable', 'channel'],
			},
		],
		label: i18n.ts.timeline,
		keywords: ['timeline'],
		path: '/settings/timeline',
		icon: 'ti ti-align-left',
	},
	{
		id: 'flXd1LC7r',
		children: [
			{
				id: 'hB11H5oul',
				label: i18n.ts.syncDeviceDarkMode,
				keywords: ['sync', 'device', 'dark', 'light', 'mode'],
			},
			{
				id: 'fDbLtIKeo',
				label: i18n.ts.themeForLightMode,
				keywords: ['light', 'theme'],
			},
			{
				id: 'CsSVILKpX',
				label: i18n.ts.themeForDarkMode,
				keywords: ['dark', 'theme'],
			},
			{
				id: '8wcoRp76b',
				label: i18n.ts.setWallpaper,
				keywords: ['wallpaper'],
			},
		],
		label: i18n.ts.theme,
		keywords: ['theme'],
		path: '/settings/theme',
		icon: 'ti ti-palette',
	},
	{
		id: 'gXe25uX7X',
		children: [
			{
				id: 'a6rIL7KId',
				label: i18n.ts.notUseSound,
				keywords: ['mute'],
			},
			{
				id: 'ux6UHdIUO',
				label: i18n.ts.useSoundOnlyWhenActive,
				keywords: ['active', 'mute'],
			},
			{
				id: 'g6lB3wZZS',
				label: i18n.ts.masterVolume,
				keywords: ['volume', 'master'],
			},
		],
		label: i18n.ts._vibrations.system,
		keywords: ['sounds', i18n.ts._settings.soundsBanner, i18n.ts.cannotBeUsedFunc],
		path: '/settings/sounds-and-vibrations',
		icon: 'ti ti-music',
	},
	{
		id: '5BjnxMfYV',
		children: [
			{
				id: '75QPEg57v',
				children: [
					{
						id: 'CiHijRkGG',
						label: i18n.ts.changePassword,
						keywords: [],
					},
				],
				label: i18n.ts.password,
				keywords: ['password'],
			},
			{
				id: '2fa',
				children: [
					{
						id: 'qCXM0HtJ7',
						label: i18n.ts.totp,
						keywords: ['totp', 'app', i18n.ts.totpDescription],
					},
					{
						id: '3g1RePuD9',
						label: i18n.ts.securityKeyAndPasskey,
						keywords: ['security', 'key', 'passkey'],
					},
					{
						id: 'pFRud5u8k',
						label: i18n.ts.passwordLessLogin,
						keywords: ['password', 'less', 'key', 'passkey', 'login', 'signin', i18n.ts.passwordLessLoginDescription],
					},
				],
				label: i18n.ts['2fa'],
				keywords: ['2fa'],
			},
		],
		label: i18n.ts.security,
		keywords: ['security', i18n.ts._settings.securityBanner],
		path: '/settings/security',
		icon: 'ti ti-lock',
	},
	{
		id: 'w4L6myH61',
		children: [
			{
				id: 'ru8DrOn3J',
				label: i18n.ts._profile.changeBanner,
				keywords: ['banner', 'change'],
			},
			{
				id: 'CCnD8Apnu',
				label: i18n.ts._profile.changeAvatar,
				keywords: ['avatar', 'icon', 'change'],
			},
			{
				id: 'yFEVCJxFX',
				label: i18n.ts._profile.name,
				keywords: ['name'],
			},
			{
				id: '2O1S5reaB',
				label: i18n.ts._profile.description,
				keywords: ['description', 'bio'],
			},
			{
				id: 'pWi4OLS8g',
				label: i18n.ts.location,
				keywords: ['location', 'locale'],
			},
			{
				id: 'oLO5X6Wtw',
				label: i18n.ts.birthday,
				keywords: ['birthday', 'birthdate', 'age'],
			},
			{
				id: 'm2trKwPgq',
				label: i18n.ts.language,
				keywords: ['language', 'locale'],
			},
			{
				id: 'kfDZxCDp9',
				label: i18n.ts._profile.metadataEdit,
				keywords: ['metadata'],
			},
			{
				id: 'uPt3MFymp',
				label: i18n.ts._profile.followedMessage,
				keywords: ['follow', 'message', i18n.ts._profile.followedMessageDescription],
			},
			{
				id: 'wuGg0tBjw',
				label: i18n.ts.reactionAcceptance,
				keywords: ['reaction'],
			},
			{
				id: 'EezPpmMnf',
				children: [
					{
						id: 'f2cRLh8ad',
						label: i18n.ts.flagAsCat,
						keywords: ['cat'],
					},
					{
						id: 'eVoViiF3h',
						label: i18n.ts.flagAsBot,
						keywords: ['bot'],
					},
				],
				label: i18n.ts.advancedSettings,
				keywords: [],
			},
		],
		label: i18n.ts.profile,
		keywords: ['profile'],
		path: '/settings/profile',
		icon: 'ti ti-user',
	},
	{
		id: '2rp9ka5Ht',
		children: [
			{
				id: 'BhAQiHogN',
				label: i18n.ts.makeFollowManuallyApprove,
				keywords: ['follow', 'lock', i18n.ts.lockedAccountInfo],
			},
			{
				id: '4DeWGsPaD',
				label: i18n.ts.autoAcceptFollowed,
				keywords: ['follow', 'auto', 'accept'],
			},
			{
				id: 'iaM6zUmO9',
				label: i18n.ts.makeReactionsPublic,
				keywords: ['reaction', 'public', i18n.ts.makeReactionsPublicDescription],
			},
			{
				id: '5Q6uhghzV',
				label: i18n.ts.followingVisibility,
				keywords: ['following', 'visibility'],
			},
			{
				id: 'pZ9q65FX5',
				label: i18n.ts.followersVisibility,
				keywords: ['follower', 'visibility'],
			},
			{
				id: 'DMS4yvAGg',
				label: i18n.ts.hideOnlineStatus,
				keywords: ['online', 'status', i18n.ts.hideOnlineStatusDescription],
			},
			{
				id: '8rEsGuN8w',
				label: i18n.ts.noCrawle,
				keywords: ['crawle', 'index', 'search', i18n.ts.noCrawleDescription],
			},
			{
				id: 's7LdSpiLn',
				label: i18n.ts.preventAiLearning,
				keywords: ['crawle', 'ai', i18n.ts.preventAiLearningDescription],
			},
			{
				id: 'l2Wf1s2ad',
				label: i18n.ts.makeExplorable,
				keywords: ['explore', i18n.ts.makeExplorableDescription],
			},
			{
				id: 'xEYlOghao',
				label: i18n.ts._chat.chatAllowedUsers,
				keywords: ['chat'],
			},
			{
				id: 'BnOtlyaAh',
				children: [
					{
						id: 'BzMIVBpL0',
						label: i18n.ts._accountSettings.requireSigninToViewContents,
						keywords: ['login', 'signin'],
					},
					{
						id: 'jJUqPqBAv',
						label: i18n.ts._accountSettings.makeNotesFollowersOnlyBefore,
						keywords: ['follower', i18n.ts._accountSettings.makeNotesFollowersOnlyBeforeDescription],
					},
					{
						id: 'ra10txIFV',
						label: i18n.ts._accountSettings.makeNotesHiddenBefore,
						keywords: ['hidden', i18n.ts._accountSettings.makeNotesHiddenBeforeDescription],
					},
				],
				label: i18n.ts.lockdown,
				keywords: ['lockdown'],
			},
		],
		label: i18n.ts.privacy,
		keywords: ['privacy', i18n.ts._settings.privacyBanner],
		path: '/settings/privacy',
		icon: 'ti ti-lock-open',
	},
	{
		id: '3yCAv0IsZ',
		children: [
			{
				id: 'AKvDrxSj5',
				children: [
					{
						id: 'a5b9RjEvq',
						label: i18n.ts.uiLanguage,
						keywords: ['language'],
					},
					{
						id: '9ragaff40',
						label: i18n.ts.overridedDeviceKind,
						keywords: ['device', 'type', 'kind', 'smartphone', 'tablet', 'desktop'],
					},
					{
						id: 'lfI3yMX9g',
						label: i18n.ts.alwaysConfirmFollow,
						keywords: ['follow', 'confirm', 'always'],
					},
					{
						id: '31Y4IcGEf',
						label: i18n.ts.confirmWhenRevealingSensitiveMedia,
						keywords: ['sensitive', 'nsfw', 'media', 'image', 'photo', 'picture', 'attachment', 'confirm'],
					},
					{
						id: '78q2asrLS',
						label: i18n.ts.enableAdvancedMfm,
						keywords: ['mfm', 'mfc', 'enable', 'show', 'advanced'],
					},
					{
						id: 'zydOfGYip',
						label: i18n.ts.enableInfiniteScroll,
						keywords: ['auto', 'load', 'auto', 'more', 'scroll'],
					},
					{
						id: 'hWVSWu1TS',
						label: i18n.ts.emojiStyle,
						keywords: ['emoji', 'style', 'native', 'system', 'fluent', 'twemoji'],
					},
				],
				label: i18n.ts.general,
				keywords: ['general'],
			},
			{
				id: 'uJkoVjTmF',
				children: [
					{
						id: '9gTCaLkIf',
						children: [
							{
								id: 'c3xhLyXZ5',
								label: i18n.ts.useBoldFont,
								keywords: ['bold'],
							},
							{
								id: 'FbhoeuRAD',
								label: i18n.ts.useSystemFont,
								keywords: ['system', 'native'],
							},
						],
						label: i18n.ts.fontSize,
						keywords: ['font', 'size'],
					},
					{
						id: 'epvi2Nv2G',
						label: i18n.ts.highlightSensitiveMedia,
						keywords: ['highlight', 'sensitive', 'nsfw', 'image', 'photo', 'picture', 'media', 'thumbnail'],
					},
					{
						id: 'v26JSj9mH',
						label: i18n.ts.squareAvatars,
						keywords: ['avatar', 'icon', 'square'],
					},
					{
						id: 'bUOs2UKY4',
						label: i18n.ts.setFederationAvatarShape,
						keywords: ['avatar', 'icon', 'square', 'federation', 'shape'],
					},
					{
						id: 'abEAdSpYY',
						label: i18n.ts.showAvatarDecorations,
						keywords: ['avatar', 'icon', 'decoration', 'show'],
					},
					{
						id: 'ytLdRjQJt',
						label: i18n.ts.showGapBetweenNotesInTimeline,
						keywords: ['note', 'timeline', 'gap'],
					},
					{
						id: '4LYTKwljE',
						label: i18n.ts.seasonalScreenEffect,
						keywords: ['effect', 'show'],
					},
					{
						id: 'jCTwaAVy',
						label: i18n.ts.showUnreadNotificationsCount,
						keywords: ['show', 'unread', 'notification', 'count'],
					},
					{
						id: 'uHcTVSGDv',
						label: i18n.ts.filesGridLayoutInUserPage,
						keywords: ['file', 'grid', 'layout', 'user', 'page', i18n.ts.filesGridLayoutInUserPageDescription],
					},
					{
						id: 'Cjn3VlODr',
						label: i18n.ts.hideAvatarsInNote,
						keywords: ['hide', 'avatar', 'note', 'display'],
					},
					{
						id: 'mNU5IBln7',
						label: i18n.ts.enableAbsoluteTime,
						keywords: ['enable', 'absolute', 'time', 'note', 'display'],
					},
					{
						id: '9dzRUAnoA',
						label: i18n.ts.enableMarkByDate,
						keywords: ['enable', 'mark', 'date', 'note', 'display'],
					},
					{
						id: 'pnCPAvH28',
						label: i18n.ts.showReplyTargetNote,
						keywords: ['show', 'reply', 'target', 'note', 'display'],
					},
					{
						id: 'clJ19wKxj',
						label: i18n.ts.showReplyTargetNoteInSemiTransparent,
						keywords: ['show', 'reply', 'target', 'note', 'transparent', 'display'],
					},
				],
				label: i18n.ts.appearance,
				keywords: ['appearance', 'display'],
			},
			{
				id: 'C3psHYdZn',
				children: [
					{
						id: 'eJ2jme16W',
						label: i18n.ts.showFixedPostForm,
						keywords: ['post', 'form', 'timeline'],
					},
					{
						id: 'qdb2U4DZy',
						label: i18n.ts.showFixedPostFormInChannel,
						keywords: ['post', 'form', 'timeline', 'channel'],
					},
					{
						id: 'eROFRMtXv',
						label: i18n.ts.showFixedPostFormInReplies,
						keywords: ['post', 'form', 'note', 'replies', i18n.ts.showFixedPostFormInRepliesDescription],
					},
					{
						id: 'C4b9owbrY',
						label: i18n.ts.forceCollapseAllRenotes,
						keywords: ['force', 'collapse', 'renote', i18n.ts.forceCollapseAllRenotesDescription],
					},
					{
						id: '4SatvrXyG',
						label: i18n.ts.collapseRenotes,
						keywords: ['renote', i18n.ts.collapseRenotesDescription],
					},
					{
						id: 'ewHkRUr4y',
						label: i18n.ts.collapseReplies,
						keywords: ['collapse', 'reply', 'replies', i18n.ts.collapseRepliesDescription],
					},
					{
						id: '98kMuzzWH',
						label: i18n.ts.collapseLongNoteContent,
						keywords: ['collapse', 'long', 'note', 'content'],
					},
					{
						id: 'eIvnR6Xxo',
						label: i18n.ts.collapseDefault,
						keywords: ['collapse', 'note'],
					},
					{
						id: 'rICn8stqk',
						label: i18n.ts.allMediaNoteCollapse,
						keywords: ['media', 'note', 'collapse'],
					},
					{
						id: 'xFmAg2tDe',
						label: i18n.ts.disableStreamingTimeline,
						keywords: ['disable', 'streaming', 'timeline'],
					},
					{
						id: 'dtw8FepYL',
						label: i18n.ts.pinnedList,
						keywords: ['pinned', 'list'],
					},
					{
						id: 'hHCRPIV4P',
						label: i18n.ts.showNoteActionsOnlyHover,
						keywords: ['hover', 'show', 'footer', 'action'],
					},
					{
						id: '2umd9GhId',
						label: i18n.ts.showClipButtonInNoteFooter,
						keywords: ['footer', 'action', 'clip', 'show'],
					},
					{
						id: '1M2u1fwhm',
						label: i18n.ts.showSubNoteFooterButton,
						keywords: ['footer', 'action', 'sub', 'note', 'show', i18n.ts.showSubNoteFooterButtonDescription],
					},
					{
						id: 'C2iXtZKb3',
						label: i18n.ts.infoButtonForNoteActions,
						keywords: ['footer', 'action', 'info', 'note', 'enable', i18n.ts.infoButtonForNoteActionsDescription],
					},
					{
						id: '2EjoyWauK',
						label: i18n.ts.showTranslateButtonInNote,
						keywords: ['note', 'action', 'translate', 'show'],
					},
					{
						id: 'xcGP5Xcit',
						label: i18n.ts.reply,
						keywords: ['reply'],
					},
					{
						id: 'oWHCVLjn0',
						label: i18n.ts.renote,
						keywords: ['renote'],
					},
					{
						id: 'zZxyXHk3A',
						label: i18n.ts.like,
						keywords: ['like'],
					},
					{
						id: 'omEy5Q3Ev',
						label: i18n.ts.doReaction,
						keywords: ['reaction', 'react'],
					},
					{
						id: 'aWitQSBtD',
						label: i18n.ts.quote,
						keywords: ['quote'],
					},
					{
						id: 'k13OE9s4H',
						label: i18n.ts.more,
						keywords: ['more'],
					},
					{
						id: 'mrueH7Rof',
						label: i18n.ts.like,
						keywords: ['like', 'select', 'reaction', 'react'],
					},
					{
						id: 'DILm2LlCn',
						label: i18n.ts.renoteQuoteButtonSeparation,
						keywords: ['renote', 'quote', 'separation', 'note'],
					},
					{
						id: 'lxXmUt7yU',
						label: i18n.ts.showRenoteVisibilitySelector,
						keywords: ['renote', 'visibility', 'selection', 'note'],
					},
					{
						id: 'n3OAGEEkP',
						label: i18n.ts.forceRenoteVisibilitySelector,
						keywords: ['force', 'renote', 'visibility', 'selection', 'note'],
					},
					{
						id: 'tb5rML3Z0',
						label: i18n.ts.showNoAltWarning,
						keywords: ['show', 'alt', 'text', 'warning', i18n.ts.showNoAltWarningDescription],
					},
					{
						id: 'gzgH25MnN',
						label: i18n.ts.alwaysShowCw,
						keywords: ['always', 'show', 'cw', 'nsfw'],
					},
					{
						id: 'tgGmMQ5k',
						label: i18n.ts.showReactionsCount,
						keywords: ['reaction', 'count', 'show'],
					},
					{
						id: 'f6J0lmg1g',
						label: i18n.ts.confirmOnReact,
						keywords: ['reaction', 'confirm'],
					},
					{
						id: 'iIFRryDW0',
						label: i18n.ts.loadRawImages,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'quality', 'raw', 'attachment'],
					},
					{
						id: '2loS8cAIS',
						label: i18n.ts.useReactionPickerForContextMenu,
						keywords: ['reaction', 'picker', 'contextmenu', 'open'],
					},
					{
						id: 'kWr3N933s',
						label: i18n.ts.reactionsDisplaySize,
						keywords: ['reaction', 'size', 'scale', 'display'],
					},
					{
						id: 'BIajBXV9u',
						label: i18n.ts.limitWidthOfReaction,
						keywords: ['reaction', 'size', 'scale', 'display', 'width', 'limit'],
					},
					{
						id: '9WVZ6t35F',
						label: i18n.ts.mediaListWithOneImageAppearance,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'list', 'size', 'height'],
					},
					{
						id: 'zeUf5ccRj',
						label: i18n.ts.instanceTicker,
						keywords: ['ticker', 'information', 'label', 'instance', 'server', 'host', 'federation'],
					},
					{
						id: 'jLUxWtnt5',
						label: i18n.ts.displayOfSensitiveMedia,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'nsfw', 'sensitive', 'display', 'show', 'hide', 'visibility'],
					},
					{
						id: 'ztwIlsXhP',
						label: i18n.ts.nsfwOpenBehavior,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'nsfw', 'sensitive', 'display', 'show', 'hide', 'visibility', 'open', 'click', 'double'],
					},
				],
				label: i18n.ts._settings.timelineAndNote,
				keywords: ['timeline', 'note'],
			},
			{
				id: 'uzdYiiO2h',
				children: [
					{
						id: '56PL3Ulr3',
						label: i18n.ts.keepCw,
						keywords: ['remember', 'keep', 'note', 'cw'],
					},
					{
						id: 'kfTVtLvgI',
						label: i18n.ts.rememberNoteVisibility,
						keywords: ['remember', 'keep', 'note', 'visibility'],
					},
					{
						id: 'urkK4xGn9',
						label: i18n.ts.enableQuickAddMfmFunction,
						keywords: ['mfm', 'mfc', 'enable', 'show', 'advanced', 'picker', 'form', 'function', 'fn'],
					},
					{
						id: 'kx7eBSeJw',
						label: i18n.ts.previewNoteText,
						keywords: ['preview', 'note', 'text'],
					},
					{
						id: 'fkqHBVTE5',
						label: i18n.ts.previewNoteProfile,
						keywords: ['show', 'profile', 'preview'],
					},
					{
						id: '7puwZRtC8',
						label: i18n.ts.defaultNoteVisibility,
						keywords: ['default', 'note', 'visibility'],
					},
				],
				label: i18n.ts.postForm,
				keywords: ['post', 'form'],
			},
			{
				id: 'dpDmRFyRj',
				children: [
					{
						id: '9wdivoAsY',
						label: i18n.ts.useGroupedNotifications,
						keywords: ['group'],
					},
					{
						id: '7KAOJKOze',
						label: i18n.ts.showReplyInNotification,
						keywords: ['show', 'reply', 'notification', 'note'],
					},
					{
						id: '2gRqygbXk',
						label: i18n.ts.position,
						keywords: ['position'],
					},
					{
						id: 'wx0Uynr0g',
						label: i18n.ts.stackAxis,
						keywords: ['stack', 'axis', 'direction'],
					},
				],
				label: i18n.ts.notifications,
				keywords: ['notification'],
			},
			{
				id: 'gI7zqJ4oS',
				label: i18n.ts._externalNavigationWarning.trustedDomainList,
				keywords: ['external', 'navigation', 'warning', i18n.ts._externalNavigationWarning.trustedDomainListDescription],
			},
			{
				id: 't0vXAerd0',
				children: [
					{
						id: 'rvlQN3ysZ',
						label: i18n.ts._settings._chat.showSenderName,
						keywords: ['show', 'sender', 'name'],
					},
					{
						id: 'xkdFyOHjo',
						label: i18n.ts._settings._chat.sendOnEnter,
						keywords: ['send', 'enter', 'newline'],
					},
				],
				label: i18n.ts.chat,
				keywords: ['chat', 'messaging'],
			},
			{
				id: 'c5qqv7zNi',
				children: [
					{
						id: 'AKocUd3X4',
						label: i18n.ts.reduceUiAnimation,
						keywords: ['animation', 'motion', 'reduce'],
					},
					{
						id: 'bO3ouRMbg',
						label: i18n.ts.disableShowingAnimatedImages,
						keywords: ['disable', 'animation', 'image', 'photo', 'picture', 'media', 'thumbnail', 'gif', i18n.ts.showingAnimatedImagesDescription],
					},
					{
						id: '6Vxf0RE4F',
						label: i18n.ts.enableAnimatedMfm,
						keywords: ['mfm', 'mfc', 'enable', 'show', 'animated'],
					},
					{
						id: '9Jd208rog',
						label: i18n.ts.enableHorizontalSwipe,
						keywords: ['swipe', 'horizontal', 'tab'],
					},
					{
						id: 'lUwqZohf4',
						label: i18n.ts.keepScreenOn,
						keywords: ['keep', 'screen', 'display', 'on'],
					},
					{
						id: '8DWlk3jZ9',
						label: i18n.ts.useNativeUIForVideoAudioPlayer,
						keywords: ['native', 'system', 'video', 'audio', 'player', 'media'],
					},
					{
						id: 'F8mx57hmG',
						label: i18n.ts._settings.makeEveryTextElementsSelectable,
						keywords: ['text', 'selectable'],
					},
					{
						id: '9m8Jq0J8P',
						label: i18n.ts.menuStyle,
						keywords: ['menu', 'style', 'popup', 'drawer'],
					},
					{
						id: 'pxHRSgfW5',
						label: i18n.ts._contextMenu.title,
						keywords: ['contextmenu', 'system', 'native'],
					},
				],
				label: i18n.ts.accessibility,
				keywords: ['accessibility', i18n.ts._settings.accessibilityBanner],
			},
			{
				id: 'wF9A1qwTJ',
				children: [
					{
						id: '1Jw81vo79',
						label: i18n.ts.turnOffToImprovePerformance,
						keywords: ['blur'],
					},
					{
						id: '6cZVdvDgT',
						label: i18n.ts.turnOffToImprovePerformance,
						keywords: ['blur', 'modal'],
					},
					{
						id: 'cm8fKwhCK',
						label: i18n.ts.removeModalBgColorForBlur,
						keywords: ['blur', 'modal', 'bg', 'remove'],
					},
					{
						id: 'wNd1H8jbr',
						label: i18n.ts.turnOffToImprovePerformance,
						keywords: ['sticky'],
					},
				],
				label: i18n.ts.performance,
				keywords: ['performance'],
			},
			{
				id: 'CdarL7s3s',
				label: i18n.ts.dataSaver,
				keywords: ['datasaver'],
			},
			{
				id: 'EPhwXMyi6',
				children: [
					{
						id: 'nwJGhJaLm',
						label: i18n.ts.openImageInNewTab,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'new', 'tab'],
					},
					{
						id: 'fsqAsUOVV',
						label: i18n.ts.withRepliesByDefaultForNewlyFollowed,
						keywords: ['follow', 'replies'],
					},
					{
						id: 'lhK30HGnK',
						label: i18n.ts.autoLoadMoreReplies,
						keywords: ['auto', 'load', 'more', 'reply', 'replies'],
					},
					{
						id: 'nNss8UFuz',
						label: i18n.ts.autoLoadMoreConversation,
						keywords: ['auto', 'load', 'more', 'conversation'],
					},
					{
						id: 'bPccCfpyC',
						label: i18n.ts.useAutoTranslate,
						keywords: ['auto', 'translate'],
					},
					{
						id: '3t2YjH4Zf',
						label: i18n.ts.welcomeBackToast,
						keywords: ['welcome', 'toast'],
					},
					{
						id: 'ba67ROXVY',
						label: i18n.ts.noNyaization,
						keywords: ['disable', 'nyaize', 'note'],
					},
					{
						id: 'jj2FudUG3',
						label: i18n.ts.whenServerDisconnected,
						keywords: ['server', 'disconnect', 'reconnect', 'reload', 'streaming'],
					},
					{
						id: 'wwJ6HMpgF',
						label: i18n.ts.requireRefresh,
						keywords: ['refresh'],
					},
					{
						id: 'Ehr5docCN',
						label: i18n.ts.newNoteReceivedNotification,
						keywords: ['note', 'receive', 'notification'],
					},
					{
						id: '68jsWjzeE',
						label: i18n.ts.numberOfPageCache,
						keywords: ['cache', 'page'],
					},
					{
						id: 'E9k731STh',
						label: i18n.ts.forceShowAds,
						keywords: ['ad', 'show'],
					},
					{
						id: 'ePN5QBOMl',
						label: i18n.ts.hemisphere,
						keywords: [],
					},
					{
						id: 'xZAoTdLJ2',
						children: [
							{
								id: 'wyY8uAGHQ',
								label: i18n.ts._searchSite.otherSearchEngine,
								keywords: [i18n.ts._searchSite.otherDescription],
							},
							{
								id: 'wGoB31TPE',
								label: i18n.ts._searchSite.query,
								keywords: [i18n.ts._searchSite.queryDescription],
							},
						],
						label: i18n.ts._searchSite.title,
						keywords: ['search', 'engine', i18n.ts._searchSite.description],
					},
					{
						id: 'Ct8nUpK8E',
						label: i18n.ts.additionalEmojiDictionary,
						keywords: ['emoji', 'dictionary', 'additional', 'extra'],
					},
				],
				label: i18n.ts.other,
				keywords: ['other'],
			},
		],
		label: i18n.ts.preferences,
		keywords: ['general', 'preferences', i18n.ts._settings.preferencesBanner],
		path: '/settings/preferences',
		icon: 'ti ti-adjustments',
	},
	{
		id: 'mwkwtw83Y',
		label: i18n.ts.plugins,
		keywords: ['plugin', 'addon', 'extension', i18n.ts._settings.pluginBanner],
		path: '/settings/plugin',
		icon: 'ti ti-plug',
	},
	{
		id: 'F1uK9ssiY',
		children: [
			{
				id: 'E0ndmaP6Q',
				label: i18n.ts._role.policies,
				keywords: ['account', 'info'],
			},
			{
				id: '8P9azj6h6',
				label: i18n.ts.rolesAssignedToMe,
				keywords: ['roles'],
			},
			{
				id: '2qI6ruPgi',
				label: i18n.ts.accountMigration,
				keywords: ['account', 'move', 'migration'],
			},
			{
				id: 'ihpEnBCat',
				label: i18n.ts.closeAccount,
				keywords: ['account', 'close', 'delete', i18n.ts._accountDelete.requestAccountDelete],
			},
			{
				id: 'DGDkl71xx',
				label: i18n.ts.truncateAccount,
				keywords: ['account', 'truncate', 'delete'],
			},
			{
				id: 'cT4d2uf9h',
				label: i18n.ts.experimentalFeatures,
				keywords: ['experimental', 'feature', 'flags'],
			},
			{
				id: 'qq8SBIFeU',
				label: i18n.ts.developer,
				keywords: ['developer', 'mode', 'debug'],
			},
		],
		label: i18n.ts.other,
		keywords: ['other'],
		path: '/settings/other',
		icon: 'ti ti-dots',
	},
	{
		id: '9bNikHWzQ',
		children: [
			{
				id: '8esviBNuv',
				label: i18n.ts.display,
				keywords: ['menu', 'display'],
			},
			{
				id: 'appYJbpkK',
				label: i18n.ts._settings.showNavbarSubButtons,
				keywords: ['navbar', 'sidebar', 'toggle', 'button', 'sub'],
			},
			{
				id: 'bR7hCS7ai',
				label: i18n.ts.displayBanner,
				keywords: ['banner', 'display'],
			},
			{
				id: 'heMIvbGju',
				label: i18n.ts.postNote,
				keywords: ['bottom'],
			},
		],
		label: i18n.ts.navbar,
		keywords: ['navbar', 'menu', 'sidebar'],
		path: '/settings/navbar',
		icon: 'ti ti-list',
	},
	{
		id: '3icEvyv2D',
		children: [
			{
				id: 'lO3uFTkPN',
				children: [
					{
						id: '5JKaXRqyt',
						label: i18n.ts.showMutedWord,
						keywords: ['show'],
					},
				],
				label: i18n.ts.wordMute,
				keywords: ['note', 'word', 'soft', 'mute', 'hide'],
			},
			{
				id: 'fMkjL3dK4',
				label: i18n.ts.hardWordMute,
				keywords: ['note', 'word', 'hard', 'mute', 'hide'],
			},
			{
				id: 'cimSzQXN0',
				label: i18n.ts.instanceMute,
				keywords: ['note', 'server', 'instance', 'host', 'federation', 'mute', 'hide'],
			},
			{
				id: 'gq8rPy3Du',
				label: `${i18n.ts.mutedUsers} (${ i18n.ts.renote })`,
				keywords: ['renote', 'mute', 'hide', 'user'],
			},
			{
				id: 'mh2r7EUbF',
				label: i18n.ts.mutedUsers,
				keywords: ['note', 'mute', 'hide', 'user'],
			},
			{
				id: 'AUS1OgHrn',
				label: i18n.ts.blockedUsers,
				keywords: ['block', 'user'],
			},
		],
		label: i18n.ts.muteAndBlock,
		keywords: ['mute', 'block', i18n.ts._settings.muteAndBlockBanner],
		path: '/settings/mute-block',
		icon: 'ti ti-ban',
	},
	{
		id: 'yR1OSyLiT',
		children: [
			{
				id: 'yMJzyzOUk',
				label: i18n.ts._emojiPalette.enableSyncBetweenDevicesForPalettes,
				keywords: ['sync', 'palettes', 'devices'],
			},
			{
				id: 'wCE09vgZr',
				label: i18n.ts._emojiPalette.paletteForMain,
				keywords: ['main', 'palette'],
			},
			{
				id: 'uCzRPrSNx',
				label: i18n.ts._emojiPalette.paletteForReaction,
				keywords: ['reaction', 'palette'],
			},
			{
				id: 'hgQr28WUk',
				children: [
					{
						id: 'fY04NIHSQ',
						label: i18n.ts.size,
						keywords: ['emoji', 'picker', 'scale', 'size'],
					},
					{
						id: '3j7vlaL7t',
						label: i18n.ts.numberOfColumn,
						keywords: ['emoji', 'picker', 'width', 'column', 'size'],
					},
					{
						id: 'zPX8z1Bcy',
						label: i18n.ts.height,
						keywords: ['emoji', 'picker', 'height', 'size'],
					},
					{
						id: '2CSkZa4tl',
						label: i18n.ts.style,
						keywords: ['emoji', 'picker', 'style'],
					},
				],
				label: i18n.ts.emojiPickerDisplay,
				keywords: ['emoji', 'picker', 'display'],
			},
		],
		label: i18n.ts.emojiPalette,
		keywords: ['emoji', 'palette'],
		path: '/settings/emoji-palette',
		icon: 'ti ti-mood-happy',
	},
	{
		id: '3Tcxw4Fwl',
		children: [
			{
				id: 'iIai9O65I',
				label: i18n.ts.emailAddress,
				keywords: ['email', 'address'],
			},
			{
				id: 'i6cC6oi0m',
				label: i18n.ts.receiveAnnouncementFromInstance,
				keywords: ['announcement', 'email'],
			},
			{
				id: 'C1YTinP11',
				label: i18n.ts.emailNotification,
				keywords: ['notification', 'email'],
			},
		],
		label: i18n.ts.email,
		keywords: ['email'],
		path: '/settings/email',
		icon: 'ti ti-mail',
	},
	{
		id: 'tnYoppRiv',
		children: [
			{
				id: 'cN3dsGNxu',
				label: i18n.ts.usageAmount,
				keywords: ['capacity', 'usage'],
			},
			{
				id: 'rOAOU2P6C',
				label: i18n.ts.statistics,
				keywords: ['statistics', 'usage'],
			},
			{
				id: 'uXGlQXATx',
				label: i18n.ts.uploadFolder,
				keywords: ['default', 'upload', 'folder'],
			},
			{
				id: 'goQdtf3dD',
				label: i18n.ts.keepOriginalFilename,
				keywords: ['keep', 'original', 'filename', i18n.ts.keepOriginalFilenameDescription],
			},
			{
				id: '83xRo0XJl',
				label: i18n.ts._imageCompressionMode.title,
				keywords: ['compression', 'compress', 'original', 'lossy', 'resize', i18n.ts._imageCompressionMode.description],
			},
			{
				id: 't6vNAKPZf',
				label: i18n.ts.alwaysMarkSensitive,
				keywords: ['always', 'default', 'mark', 'nsfw', 'sensitive', 'media', 'file'],
			},
			{
				id: '3UQ6CsWXI',
				label: i18n.ts.enableAutoSensitive,
				keywords: ['auto', 'nsfw', 'sensitive', 'media', 'file', i18n.ts.enableAutoSensitiveDescription],
			},
		],
		label: i18n.ts.drive,
		keywords: ['drive', i18n.ts._settings.driveBanner],
		path: '/settings/drive',
		icon: 'ti ti-cloud',
	},
	{
		id: 'FfZdOs8y',
		children: [
			{
				id: 'B1ZU6Ur54',
				label: i18n.ts._deck.enableSyncBetweenDevicesForProfiles,
				keywords: ['sync', 'profiles', 'devices'],
			},
			{
				id: 'iEF0gqNAo',
				label: i18n.ts._deck.useSimpleUiForNonRootPages,
				keywords: ['ui', 'root', 'page'],
			},
			{
				id: 'BNdSeWxZn',
				label: i18n.ts.defaultNavigationBehaviour,
				keywords: ['default', 'navigation', 'behaviour', 'window'],
			},
			{
				id: 'zT9pGm8DF',
				label: i18n.ts._deck.alwaysShowMainColumn,
				keywords: ['always', 'show', 'main', 'column'],
			},
			{
				id: '5dk2xv1vc',
				label: i18n.ts._deck.columnAlign,
				keywords: ['column', 'align'],
			},
			{
				id: 'gtdEA4FTa',
				label: i18n.ts._deck.deckMenuPosition,
				keywords: ['menu', 'position'],
			},
			{
				id: 'DHVFdPBT6',
				label: i18n.ts._deck.navbarPosition,
				keywords: ['navbar', 'position'],
			},
			{
				id: '3UQ8rUssZ',
				label: i18n.ts._deck.columnGap,
				keywords: ['column', 'gap', 'margin'],
			},
		],
		label: i18n.ts.deck,
		keywords: ['deck', 'ui'],
		path: '/settings/deck',
		icon: 'ti ti-columns',
	},
	{
		id: 'BlJ2rsw9h',
		children: [
			{
				id: '9bLU1nIjt',
				label: i18n.ts._settings.api,
				keywords: ['api', 'app', 'token', 'accessToken'],
			},
			{
				id: '5VSGOVYR0',
				label: i18n.ts._settings.webhook,
				keywords: ['webhook'],
			},
		],
		label: i18n.ts._settings.serviceConnection,
		keywords: ['app', 'service', 'connect', 'webhook', 'api', 'token', i18n.ts._settings.serviceConnectionBanner],
		path: '/settings/connect',
		icon: 'ti ti-link',
	},
	{
		id: '2HuxtgWa1',
		children: [
			{
				id: '9qNB7raTE',
				label: i18n.ts._cherrypick.nickname,
				keywords: ['nickname', 'enable', i18n.ts._cherrypick.nicknameDescription],
			},
			{
				id: 'DyKDeHONI',
				label: i18n.ts._cherrypick.useEnterToSend,
				keywords: ['nickname', 'enable', i18n.ts._cherrypick.useEnterToSendDescription],
			},
			{
				id: 'qBKqephVl',
				label: i18n.ts._cherrypick.postFormVisibilityHotkey,
				keywords: ['post', 'form', 'visibility', 'hotkey', i18n.ts._cherrypick.postFormVisibilityHotkeyDescription],
			},
			{
				id: 'eEA7ytlZ5',
				label: i18n.ts._cherrypick.showRenoteConfirmPopup,
				keywords: ['show', 'renote', 'note', 'confirm', 'popup', i18n.ts._cherrypick.showRenoteConfirmPopupDescription],
			},
			{
				id: 'lgY6Zesu0',
				children: [
					{
						id: '4YCeZiMxo',
						label: i18n.ts._cherrypick.expandOnNoteClickBehavior,
						keywords: ['behavior'],
					},
				],
				label: i18n.ts._cherrypick.expandOnNoteClick,
				keywords: ['expand', 'note', 'click', i18n.ts._cherrypick.expandOnNoteClickDescription],
			},
			{
				id: 'kxtO1YGjn',
				label: i18n.ts._cherrypick.displayHeaderNavBarWhenScroll,
				keywords: ['display', 'header', 'navbar', 'scroll'],
			},
			{
				id: 'ucJrWjNkp',
				children: [
					{
						id: 'abmEqjbI9',
						label: i18n.ts._cherrypick.reactableRemoteReaction,
						keywords: ['reactable', 'remote', 'reaction', 'react', 'enable'],
					},
					{
						id: 'vrQyQ7OAC',
						label: i18n.ts._cherrypick.showFollowingMessageInsteadOfButton,
						keywords: ['show', 'follow', 'message', 'enable'],
					},
					{
						id: '9MWRArjLD',
						label: i18n.ts._cherrypick.mobileHeaderChange,
						keywords: ['mobile', 'header', 'change'],
					},
					{
						id: '5db7W0B5j',
						label: i18n.ts._cherrypick.renameTheButtonInPostFormToNya,
						keywords: ['rename', 'post', 'form', 'nya', i18n.ts._cherrypick.renameTheButtonInPostFormToNyaDescription],
					},
				],
				label: i18n.ts._cherrypick.patch,
				keywords: ['patch', 'behavior', i18n.ts._cherrypick.patchDescription],
			},
			{
				id: 'cBQaz6sa0',
				children: [
					{
						id: 'Cs2cPX8pY',
						label: i18n.ts._cherrypick.enableWidgetsArea,
						keywords: ['enable', 'widget'],
					},
					{
						id: 'hZnNBcUjw',
						children: [
							{
								id: 'x2O7OsvzW',
								label: i18n.ts._cherrypick.friendlyUiEnableNotificationsArea,
								keywords: ['enable', 'notification'],
							},
							{
								id: 'f0HK0WoY2',
								label: i18n.ts._cherrypick.enableLongPressOpenAccountMenu,
								keywords: ['enable', 'long', 'press', 'open', 'account', 'menu', i18n.ts._cherrypick.enableLongPressOpenAccountMenuDescription],
							},
							{
								id: 'aiUEVAQSz',
								label: i18n.ts._cherrypick.friendlyUiShowAvatarDecorationsInNavBtn,
								keywords: ['show', 'avatar', 'decoration', 'navbtn'],
							},
						],
						label: 'Friendly UI',
						keywords: ['friendly'],
					},
				],
				label: 'UI',
				keywords: ['ui', 'show', 'display'],
			},
			{
				id: 'BhJb8gpN0',
				label: i18n.ts.cherrypickLabs,
				keywords: ['behavior', 'lab', i18n.ts.cherrypickLabsDescription],
			},
		],
		label: i18n.ts._cherrypick.function,
		keywords: ['cherrypick', i18n.ts._cherrypick.functionDescription],
		path: '/settings/cherrypick',
		icon: 'ti ti-bulb-filled',
	},
	{
		id: 'gtaOSdIJB',
		label: i18n.ts.avatarDecorations,
		keywords: ['avatar', 'icon', 'decoration'],
		path: '/settings/avatar-decoration',
		icon: 'ti ti-sparkles',
	},
	{
		id: 'zK6posor9',
		label: i18n.ts.accounts,
		keywords: ['accounts'],
		path: '/settings/accounts',
		icon: 'ti ti-users',
	},
	{
		id: '330Q4mf8E',
		children: [
			{
				id: 'eGSjUDIKu',
				label: i18n.ts._exportOrImport.allNotes,
				keywords: ['notes'],
			},
			{
				id: 'iMDgUVgRu',
				label: i18n.ts._exportOrImport.favoritedNotes,
				keywords: ['favorite', 'notes'],
			},
			{
				id: '3y6KgkVbT',
				label: i18n.ts._exportOrImport.clips,
				keywords: ['clip', 'notes'],
			},
			{
				id: 'cKiHkj8HE',
				label: i18n.ts._exportOrImport.followingList,
				keywords: ['following', 'users'],
			},
			{
				id: '3zzmQXn0t',
				label: i18n.ts._exportOrImport.userLists,
				keywords: ['user', 'lists'],
			},
			{
				id: '3ZGXcEqWZ',
				label: i18n.ts._exportOrImport.muteList,
				keywords: ['mute', 'users'],
			},
			{
				id: '84oL7B1Dr',
				label: i18n.ts._exportOrImport.blockingList,
				keywords: ['block', 'users'],
			},
			{
				id: 'ckqi48Kbl',
				label: i18n.ts.antennas,
				keywords: ['antennas'],
			},
		],
		label: i18n.ts._settings.accountData,
		keywords: ['import', 'export', 'data', 'archive', i18n.ts._settings.accountDataBanner],
		path: '/settings/account-data',
		icon: 'ti ti-package',
	},
] as const;

export type SearchIndex = typeof searchIndexes;
