FROM alpine:latest
RUN apk update && apk add curl unzip
WORKDIR /sudachi-dictionary

RUN curl -sSL -o sudachi-dictionary-core.zip https://github.com/WorksApplications/SudachiDict/releases/download/v20240409/sudachi-dictionary-20240409-core.zip
RUN unzip sudachi-dictionary-core.zip

RUN curl -sSL -o sudachi-dictionary.zip https://github.com/WorksApplications/SudachiDict/releases/download/v20240409/sudachi-dictionary-20240409-full.zip
RUN unzip -o sudachi-dictionary.zip

FROM opensearchproject/opensearch:2.14.0
RUN /usr/share/opensearch/bin/opensearch-plugin install --batch \
    https://github.com/WorksApplications/elasticsearch-sudachi/releases/download/v3.2.2/opensearch-2.14.0-analysis-sudachi-3.2.2.zip
COPY --from=0 /sudachi-dictionary/sudachi-dictionary-20240409 config/sudachi/
