services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules

    command: sleep infinity

    networks:
      - internal_network
      - external_network

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: unless-stopped
    image: postgres:15-alpine
    networks:
      - internal_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cherrypick
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

volumes:
  postgres-data:
  redis-data:
  node_modules:

networks:
  internal_network:
    internal: true
  external_network:
