name: Check the description in CHANGELOG_CHERRYPICK.md

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout head
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: '.node-version'

      - name: Checkout base
        run: |
          mkdir _base
          cp -r .git _base/.git
          cd _base
          git fetch --depth 1 origin ${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }} CHANGELOG_CHERRYPICK.md

      - name: Copy to Checker directory for CHANGELOG_CHERRYPICK-base.md
        run: cp _base/CHANGELOG_CHERRYPICK.md scripts/changelog-checker/CHANGELOG_CHERRYPICK-base.md
      - name: Copy to Checker directory for CHANGELOG_CHERRYPICK-head.md
        run: cp CHANGELOG_CHERRYPICK.md scripts/changelog-checker/CHANGELOG_CHERRYPICK-head.md
      - name: diff
        continue-on-error: true
        run: diff -u CHANGELOG_CHERRYPICK-base.md CHANGELOG_CHERRYPICK-head.md
        working-directory: scripts/changelog-checker

      - name: Setup Checker
        run: npm install
        working-directory: scripts/changelog-checker
      - name: Run Checker
        run: npm run run
        working-directory: scripts/changelog-checker
